export const ROOT_MOUNTED = 'ROOT_MOUNTED';

// triggered by user
export const CLICKED_SHOW_EDIT_RECIPE = 'CLICKED_SHOW_EDIT_RECIPE';
export const CLICKED_SAVE_RECIPE = 'CLICKED_SAVE_RECIPE';
export const CLICKED_UPDATE_RECIPE = 'CLICKED_UPDATE_RECIPE';
export const CLICKED_CANCEL_RECIPE = 'CLICKED_CANCEL_RECIPE';
export const CLICKED_CANCEL_NEW_RECIPE = 'CLICKED_CANCEL_NEW_RECIPE';
export const CLICKED_SHOW_ADD_RECIPE = 'CLICKED_SHOW_ADD_RECIPE';
export const CLICKED_TEST_NEW_RECIPE = 'CLICKED_TEST_NEW_RECIPE';
export const CLICKED_PUBLISH = 'CLICKED_PUBLISH';

// firebase triggered
export const RECEIVED_FROM_TESTS = 'RECEIVED_FROM_TESTS';
export const CREATED_IN_TESTS = 'CREATED_IN_TESTS';
export const CREATE_FAILED_IN_TESTS = 'CREATE_FAILED_IN_TESTS';
export const UPDATED_IN_TESTS = 'UPDATED_IN_TESTS';
export const UPDATE_FAILED_IN_TESTS = 'UPDATE_FAILED_IN_TESTS';

export const RECEIVED_FROM_TEST_RESULTS = 'RECEIVED_FROM_TEST_RESULTS';

export const RECEIVED_FROM_AGENT = 'RECEIVED_FROM_AGENT';

export const RECEIVED_FROM_RECIPES = 'RECEIVED_FROM_RECIPES';
export const CREATED_IN_RECIPES = 'CREATED_IN_RECIPES';
export const CREATE_FAILED_IN_RECIPES = 'CREATE_FAILED_IN_RECIPES';
export const UPDATED_IN_RECIPES = 'UPDATED_IN_RECIPES';
export const UPDATE_FAILED_IN_RECIPES = 'UPDATE_FAILED_IN_RECIPES';

