export const APP_MOUNTED = 'APP_MOUNTED';

// triggered by user
export const CLICKED_SHOW_EDIT_RECIPE = 'CLICKED_SHOW_EDIT_RECIPE';
export const CLICKED_SAVE_RECIPE = 'CLICKED_SAVE_RECIPE';
export const CLICKED_UPDATE_RECIPE = 'CLICKED_UPDATE_RECIPE';
export const CLICKED_CANCEL_RECIPE = 'CLICKED_CANCEL_RECIPE';
export const CLICKED_CANCEL_NEW_RECIPE = 'CLICKED_CANCEL_NEW_RECIPE';
export const CLICKED_SHOW_ADD_RECIPE = 'CLICKED_SHOW_ADD_RECIPE';
export const CLICKED_TEST_NEW_RECIPE = 'CLICKED_TEST_NEW_RECIPE'; // TODO remove when implemented via Epic
export const CLICKED_PUBLISH = 'CLICKED_PUBLISH';
export const CLICKED_TEST_RECIPE = 'CLICKED_TEST_RECIPE';


// firebase triggered
export const RECIPE_SAVED_OK = 'RECIPE_SAVED_OK'; // callback triggered
export const RECIPE_SAVE_FAILED = 'RECIPE_SAVE_FAILED';
export const TEST_SAVED_OK = 'TEST_SAVED_OK';
export const TEST_SAVE_FAILED = 'TEST_SAVE_FAILED';

export const RECEIVED_FROM_TESTS = 'RECEIVED_FROM_TESTS';
export const CREATED_IN_TESTS = 'CREATED_IN_TESTS';
export const CREATE_FAILED_IN_TESTS = 'CREATE_FAILED_IN_TESTS';
export const UPDATED_IN_TESTS = 'UPDATED_IN_TESTS';
export const UPDATE_FAILED_IN_TESTS = 'UPDATE_FAILED_IN_TESTS';

export const RECEIVED_FROM_TEST_RESULTS = 'RECEIVED_FROM_TEST_RESULTS';

export const RECEIVED_FROM_AGENT = 'RECEIVED_FROM_AGENT';

export const RECEIVED_FROM_RECIPES = 'RECEIVED_FROM_RECIPES';
export const CREATED_IN_RECIPES = 'CREATED_IN_RECIPES';
export const CREATE_FAILED_IN_RECIPES = 'CREATE_FAILED_IN_RECIPES';
export const UPDATED_IN_RECIPES = 'UPDATED_IN_RECIPES';
export const UPDATE_FAILED_IN_RECIPES = 'UPDATE_FAILED_IN_RECIPES';

